### ISSUE TITLE
Yahoo problems

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#81] opened 2023-01-20 13:55 UTC
I have not been able to use my spreadsheet since last Friday (7 days). This is for the same reason that others have reported. During that time the extension has not been  able to obtain any meaningful data from the Yahoo site.

**Comment by cmallwitz** [comment] 2023-01-20 16:10
Closing as duplicate of https://github.com/cmallwitz/Financials-Extension/issues/80

**Closed by cmallwitz** 2023-01-20 16:10 UTC
