### ISSUE TITLE
looks like Yahoo changed again

### ISSUE THREAD

**Issue by criddle3** [cmallwitz/Financials-Extension#98] opened 2024-01-30 22:44 UTC
=GETREALTIME(B4,21,"YAHOO") returns #N/A for all requests. As do Previous Close, Day Change, Percent Change

**Comment by cmallwitz** [comment] 2024-01-31 09:57
Can you try the latest release https://github.com/cmallwitz/Financials-Extension/releases/tag/3.4.0

**Comment by criddle3** [comment] 2024-01-31 13:37
Tried that first. Updated yesterday before posting this. It worked fine up until the morning of 1/30/24

![image](https://github.com/cmallwitz/Financials-Extension/assets/48762890/3f805c20-bbc7-4c6b-aca6-a6ba2dad540c)

**Comment by spacecatz03** [comment] 2024-01-31 14:44
Just FYI, I had the #N/A issues as well, just uninstalled old added new, now works like a charm again. Thanks.

**Comment by criddle3** [comment] 2024-01-31 14:51
Got it
in my case:
Uninstall -> Install -> Restart - still failed to pull
Uninstall -> Restart -> Install -> Restart - working again

Thanks all

**Comment by cmallwitz** [comment] 2024-01-31 17:53
Good to hear - unfortunately, on that level it is all LibreCalc's doing, not mine...

**Comment by cmallwitz** [comment] 2024-02-01 13:37
I'm still on 7.3 too (Ubuntu 20.04) and it is working so I was hoping everyone else would be fine too. Unfortunately a LC extension has basically no chance to deal with any issues in a local LC installation. It just gets called and if it isn't, it doesn't even know about it.

**Comment by techman2423** [comment] 2024-02-05 19:25
> Got it in my case: Uninstall -> Install -> Restart - still failed to pull Uninstall -> Restart -> Install -> Restart - working again
> 
> Thanks all

i had the same issue and ended up installing the same to get rid of issue last week.  however it's back again today.  I had to repeat this process....remove 3.4.0 (new) and restart.  install new and restart.  runs again...

**Comment by spacecatz03** [comment] 2024-02-06 14:58
Just an FYI, I got another #N/A, initially this morning but then realized it was a VPN issue, if I pause the VPN connection it will update but otherwise, may not.

**Comment by techman2423** [comment] 2024-02-08 01:17
Its still doing it. I'll run through the uninstall, restart, install, restart again.

**Comment by dtw2000** [comment] 2024-02-10 04:11
@cmallwitz I'm not sure this is helpful.  I have a few linux machines (mint/ubuntu) on 7.3 and a windows machine - was on 7.3 upgraded to 7.6 because of this "issue".  I have a file that is synced through syncthing that I open on the various machines.  I seem to get the N/A issue very consistently every time I open the file on a different machine; however, I consistently fix it by disabling/enabling the extension which requires a restart of libre.  I followed the other suggestion of uninstall/reinstall and thought, cool that works, so I did it on all my machines.  Then, I kept getting the error.  Trial and error suggested that disable/enable/restart seems to fix the issue almost every time. Sometimes 2x of disable/enable/restart is the key.  Does that help any?

**Comment by techman2423** [comment] 2024-02-11 00:29
Yes in fact the disable/reenable with restarts worked. It was random how many I had to do to make it finally work.

 Any idea why this is going on?



On Feb 9, 2024, at 10:11 PM, dtw2000 ***@***.***> wrote:

﻿

@cmallwitz<https://github.com/cmallwitz> I'm not sure this is helpful. I have a few linux machines (mint/ubuntu) on 7.3 and a windows machine - was on 7.3 upgraded to 7.6 because of this "issue". I have a file that is synced through syncthing that I open on the various machines. I seem to get the N/A issue very consistently every time I open the file on a different machine; however, I consistently fix it by disabling/enabling the extension which requires a restart of libre. I followed the other suggestion of uninstall/reinstall and thought, cool that works, so I did it on all my machines. Then, I kept getting the error. Trial and error suggested that disable/enable/restart seems to fix the issue almost every time. Sometimes 2x of disable/enable/restart is the key. Does that help any?

**Comment by zamar** [comment] 2024-02-28 04:59
I just hit this issue. Uninstalling + Reinstalling twice resolved the problem.

**Comment by eford321** [comment] 2024-03-01 19:32
This problem continues for me. Sometimes uninstall/reinstall with restarts works, but only for a short while.  Disable/reenable does not work for me.

**Comment by zamar** [comment] 2024-03-02 21:05
I'm seeing the same. Sometimes uninstall/reinstall solves the problem. Then it might work again for a little while, and then the problem reappears.

**Comment by Futur3H4wk** [comment] 2024-03-05 20:27
for a while now, disable restart enable restart has been working for me. today did this twice several different error messages no joy. uninstall restart install restart still no joy. I don't check what updates and when I have a script that updates all my programs be they manually installed, aptitude , or flatpack. I just run it a few times a day. so if libre made an update i probably installed it without even knowing it. What ever the cause this issue persists.

**Comment by cmallwitz** [comment] 2024-03-05 20:41
I have no idea why deinstalling/installing the extension would change anything. The extension is a python script with a exposed function that gets called for every formula you have in a spread sheet. the script is put in a ZIP file, the ZIP extension is renamed and when the LC extension manger install the extension, it is unzipped to a user specific directory. As far as I'm aware no modifications are done in the installation step to any of the files in the extension.

if you put =GETREALTIME("SUPPORT") in a cell, you can see some of the information available to the extension on your system including file=... pointing to main, unzipped extension script. 

BTW what system are you on? could anything modify files in the installation directory of the extension?

**Comment by Futur3H4wk** [comment] 2024-03-05 20:59
https://termbin.com/phr0

It's a VBox

Linux 5.15.0-97-generic - Mint 21.2 - Cinnamon 5.8.4 - 13th Gen Intel© Core™ i5-13600K × 1 - memory 19.1 GiB

Version: 24.2.1.2 (X86_64) / LibreOffice Community
Build ID: db4def46b0453cc22e2d0305797cf981b68ef5ac
CPU threads: 1; OS: Linux 5.15; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Flatpak
Calc: threaded

I don't see a zip file I probably deleted it
Financials-Extension.oxt
Sun 05 Feb 2023 11:42:14 AM EST

As to files being modified, I'm not that good with programming I just download and follow the read-me file. So it's possible

**Comment by beckjake** [comment] 2024-03-06 01:03
It's not necessary to uninstall + reinstall the extension to fix the issue, it's enough to close and re-open calc. It can take a few tries.


My `=GETREALTIME("SUPPORT") ` output:
```
ctx=pyuno object (com.sun.star.uno.XComponentContext)0x59f6aed3f548{, supportedInterfaces={com.sun.star.uno.XWeak,com.sun.star.lang.XComponent,com.sun.star.lang.XTypeProvider,com.sun.star.uno.XComponentContext,com.sun.star.container.XNameContainer}}
id(self)=138356130421328
version=3.4.0
file=/home/<username>/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu184479zgrpi.tmp_/Financials-Extension.oxt/financials.py
cwd=/home/<username>/Documents
home=/home/<username>
uname=Linux <hostname> 6.7.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000 x86_64 
pid=12681
sys.executable=/usr/bin/python3
sys.version=3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]
sys.path=['/home/<username>/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu184479zgrpi.tmp_/Financials-Extension.oxt', '/usr/lib/libreoffice/program', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
locale=('en_US', 'UTF-8')
defaultlocale=('en_US', 'UTF-8')
dateutil=2.8.2
pytz=2023.3
pyparsing=2.4.7
six=1.16.0
```

There's no obvious difference in the above output between the working and non-working states (PID and the memory address of the pyuno object is it). Last time it wasn't working I looked at the html files and they had the tags I'd expect.

**Comment by Futur3H4wk** [comment] 2024-03-06 07:26
Uninstalling and reinstalling never seemed to make a dif for me. but including that I've disabled and reenabled at least 5 times. and run an update script. still no joy. wish I could be of more help but point and click is about the best I can do.

**Comment by spacecatz03** [comment] 2024-03-06 17:12
FWIW, this has been happening to me more frequently (like right now), I just close LibreOffice, wait a minute or 2 and then it's
usually okay.

**Comment by Futur3H4wk** [comment] 2024-03-08 06:43
Several days and multiple system reboots and still no joy. Ubuntu even pushed a kernel update today and still not working. I love this extension and to be honest I’m a little lost when it’s not working. Now I’m noticing a separate issue with my vbox and NoMachine resurfacing, The joys of Linux when you’re not a coder.

**Comment by estianic** [comment] 2024-03-08 10:06
Works fine here on native Mint 21.3/Kernel 6.1.0/Libreoffice 7.3.7.2 (distro version)/extension 3.4.0

=GETREALTIME("SUPPORT"):

ctx=pyuno object (com.sun.star.uno.XComponentContext)0x55c769882c00{, supportedInterfaces={com.sun.star.uno.XComponentContext,com.sun.star.container.XNameContainer,com.sun.star.lang.XTypeProvider,com.sun.star.uno.XWeak,com.sun.star.lang.XComponent}}
id(self)=140004769450784
version=3.4.0
file=/home/<username>/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu647034xzn.tmp_/Financials-Extension.oxt/financials.py
cwd=/home/<username>
home=/home/<username>
uname=Linux <hostname> 6.1.0-1034-oem #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb  5 18:29:21 UTC 2024 x86_64 x86_64
pid=65346
sys.executable=/usr/bin/python3
sys.version=3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.path=['/home/<username>/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu647034xzn.tmp_/Financials-Extension.oxt', '/usr/lib/libreoffice/program', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages', '/usr/lib/libreoffice/program']
locale=('en_US', 'UTF-8')
defaultlocale=('en_US', 'UTF-8')
dateutil=2.8.2
pytz=2023.3
pyparsing=2.4.7
six=1.16.0

**Comment by beckjake** [comment] 2024-03-08 14:53
I ran the existing html file through the parser manually in ipython and then started doing the steps from [here](https://github.com/cmallwitz/Financials-Extension/blob/88b039d47104d8388db9a7d39d7f8b60f17b9dde/src/financials_yahoo.py#L223) onwards.

I noticed there was no attribute named 'value' on `d` when I got to [here](https://github.com/cmallwitz/Financials-Extension/blob/88b039d47104d8388db9a7d39d7f8b60f17b9dde/src/financials_yahoo.py#L228), but there is an attribute named 'data-value' that looked like the exact value I wanted. I updated the code there to be `(default(d.attrib, 'value') or default(d.attrib, 'data-value'))` in place of the existing `default(d.attrib, 'value')`, and have successfully restarted libreoffice multiple times and always get the values.

I tested it out by adding a `if default(d.attrib, 'data-value') and not default(d.attrib, 'value'): logger.error("data-value and no value")`, and indeed, I see it in extension.log a bunch.

If I have time this weekend I can open a PR for this, but feel free to just do it yourself if you have the time. Perhaps Yahoo Finance is A/B testing a new response format.

**Comment by beckjake** [comment] 2024-03-09 04:47
@Durhammer3111 

I just hit the same error you got, though for me it looked like the files hadn't downloaded at all - which I think makes more sense, given the error and where the stack trace is pointing. I added some logging around the problem area but then couldn't reproduce it. It's probably small solace, but rest assured, it's not just you :). That error manifests much differently than the `data-value` one I hit earlier, it's some sort of error I failed to capture as opposed to the `data-value` issue's `N/A` result. What it kind of looked like to me was that maybe I was getting blocked entirely. This might seem like kind of a silly question, but can you access yahoo finance from your browser when you're having this problem? I sort of wish I was able to hit this consistently, as it'd be easier to debug.


Also, so far as I can tell there's no need to go through uninstalling + reinstalling the extension. You can just close and re-open libreoffice for the same effect. Possibly even doing a simple ctrl+shift+f9 (refresh all cells, which ends up re-doing the http queries as long as it's been more than a minute or so) is sufficient.

**Comment by Durhammer3111** [comment] 2024-03-09 15:33
Hi @beckjake -- yes, I keep a Yahoo! tab open in my browser all the time, use it regularly, and have no problem there. This issue has been ongoing for me since March 5. And as @Futur3H4wk said, I'm kinda dead in the water when it's not working. @cmallwitz  has built us a wonderful, addictive magical black box. and now I've got the shakes in withdrawal....

**Comment by Durhammer3111** [comment] 2024-03-09 16:23
Soooo, @cmallwitz or anyone else who knows how to code Python and such, is there a simple way to turn on any useful debug logging that might help here?

**Comment by eford321** [comment] 2024-03-09 18:23
> This might seem like kind of a silly question, but can you access yahoo finance from your browser when you're having this problem? 

Browser works fine for me also.

**Comment by estianic** [comment] 2024-03-10 15:07
If it looks like the .html files aren't downloaded or they are very small, I think that points to a cookie problem.

First step would be to delete yahoo.cookiejar in the extension directory (.financials-extension on Linux).

**Comment by Durhammer3111** [comment] 2024-03-10 15:39
Hi @estianic -- your comment makes me think you're on an older version of the extension. @cmallwitz changed it at some point so that there no longer is a cookie file.

**Comment by Futur3H4wk** [comment] 2024-03-10 15:48
I'm running 3.3.0 and after deleting .financials-extension and launcinig librecalc the file reapeared. also did not fix the proiblem

**Comment by Durhammer3111** [comment] 2024-03-11 01:38
- For what it's worth, I've been playing around with some Linux commands (curl, pup, etc.) in thoughts of building a bash-based system. Interestingly enough, I'm seeing some weird results when trying to use curl to download some Yahoo! files that should be there. It seems to happen most with preferred stock tickers -- for example, I get 404 errors with QRTEP, CDR-PC, and OPINL, while CCLDP is fine. Go figure. So far, no problem with regular stock tickers.  Something's weird on the Yahoo end. The game is afoot.

**Comment by estianic** [comment] 2024-03-11 11:02
You're right, there is no cookie file anymore, I'm using extension version 3.4.0

Nevertheless, I still think it has something to do with the way cookies are handled. Someone suggested that Yahoo is doing A/B testing, because for some of us (like me) the extension still works fine. Cookies are handled differently in different countries because of legal differences. 

These Yahoo .html files that refuse to download and are very small, what happens when you open them in a browser ? Blurred text ?

**Comment by cmallwitz** [comment] 2024-03-11 13:39
When you get errors and see a very small yahoo*.html saved to .financials-extension/, could you send/attach it here?

**Comment by Durhammer3111** [comment] 2024-03-11 15:14
Well, I WOULD, but when I click on the paperclip tool to attach one of the files, they simply don't show up. Ah, that's probably because they're .html files. But here's what yahoo-DECK.html looks like:

**Comment by cmallwitz** [comment] 2024-03-11 15:16
ah, so there is content whatsoever...

**Comment by Durhammer3111** [comment] 2024-03-11 15:56
Right. I have no problem viewing the DECK quote page nor downloading it via curl:

`curl -k -L -s --compressed https://finance.yahoo.com/quote/DECK > myyahoo-DECK.html`

**Comment by Durhammer3111** [comment] 2024-03-11 16:04
HOWEVER, as with certain tickers I previously mentioned, trying to download the statistics* file for DECK gets me a "404" error file.

*i. e., `https://finance.yahoo.com/quote/DECK/key-statistics`

**Comment by Futur3H4wk** [comment] 2024-03-11 18:11
just updated to 3.4.0 still no luck. I made a tar file of the .finan* file and dropped the . off the front. not sure if this is helpful
[financials-extension.tar.gz](https://github.com/cmallwitz/Financials-Extension/files/14562833/financials-extension.tar.gz)

**Comment by Durhammer3111** [comment] 2024-03-11 19:45
FWIW, I just made a "FT" copy of my spreadsheet, added all the various exchange suffixes (sheesh -- a lot, and it just looks ugly!), and changes all the function calls from "YAHOO" to "FT" and it works. Even has decent speed! There are some odd differences, such as the market cap is only shown in M in FT (Yahoo shows 'em in B if apropos), and the daily % change is 100 times what it should be. Thanks for giving us that option, @cmallwitz !  I'll keep fiddling with it to make it so the symbols are nicer, maybe by having a hidden cell with the exchange that can be concatenated onto the ticker (won't work for CDR-PC, tho -- sheesh!).

**Comment by cmallwitz** [comment] 2024-03-13 12:16
I have integrated the pull request from [beckjake](https://github.com/cmallwitz/Financials-Extension/commits?author=beckjake) and created release version [3.5.0](https://github.com/cmallwitz/Financials-Extension/releases/tag/3.5.0) - let us know if this improves things for you.

**Comment by Durhammer3111** [comment] 2024-03-13 14:07
YAY -- it's now working again with Yahoo!! While I now have a backup scheme to allow flipping betwixt Yahoo! and FT, Yahoo! has far better better data point availability. Thanks, @cmallwitz !

**Comment by cmallwitz** [comment] 2024-03-13 14:25
I still have no idea how Yahoo manages to generate different HTML depending on location. Maybe you guys having problems can share details about your location and/or internet provider. and if any of you has VPN available, is activating it to somewhere else actually fixing your problems?

When releasing I try to run a few tests while on VPN to UK , EU, US just to make sure there are no obvious changes to cookie handling depending on jurisdiction but so far I have not seen your problem locally...

**Comment by techman2423** [comment] 2024-03-13 14:38
I had a checking a time getting it to work yesterday. Finally did. I’m in Oklahoma with OEC as my provider. Fiber connection. Haven’t had any issues network wise with anything else.

**Comment by beckjake** [comment] 2024-03-13 14:39
For me, the new html seemed roughly correlated with the appearance of yahoo's new (slow and buggy) UI. If I navigate to a stock ticker page in yahoo using the new UI and "view source", I can find `data-value`. If I switch it back to the "classic yahoo finance" view, I can't find `data-value` in the source anymore. I've been getting  A/B tested about it for a while now but the default seems to be "new".

**Comment by Durhammer3111** [comment] 2024-03-13 14:39
Actually, I now wonder if one of my issues was of shooting myself in the foot when I did the "remove/reinstall" of the extension. When I upgraded to the 3.5.0 extension, I noticed in Calc's extension manager that the listed version was 3.2.1 !!! Maybe the version could be incorporated into the file name?

**Comment by cmallwitz** [comment] 2024-03-13 15:07
Re: adding version to extension filename - Libre Calc is rather finicky about this. Users have done this while doing a "Save As" from browser and it turns out this breaks the installation process in Extension Manager. But maybe I need to generate the version somehow into the meta data inside the extension in order to get this to work...

**Comment by Durhammer3111** [comment] 2024-03-13 15:20
You have a tough job, my friend! And we all appreciate the work you do!

**Comment by craig2sigma** [comment] 2024-03-13 15:46
I applied 3.5. The past several days with the old version took several minutes each time I did a refresh. This new version seem to be back to about the same speed as it was in the past. That's a win. So far not getting the massive failure on everything. Another win. I am seeing two pulls failing now though. The previous close, =GETREALTIME(B6,5,"YAHOO"), gives me #N/A for all rows. The percent change, =GETREALTIME(B6,11,"YAHOO"), is giving weird, inaccurate numbers and scattered #N/A

**Comment by cmallwitz** [comment] 2024-03-13 15:49
What does your B6 cell contain?

13 Mar 2024 16:46:30 craig2sigma ***@***.***>:

**Comment by craig2sigma** [comment] 2024-03-13 15:52
The Stock Symbol. examples: PLTR NVDA

**Comment by Durhammer3111** [comment] 2024-03-13 15:55
I'm using 11 to get the % change and it's working fine for me. I use indirect addressing to get the cells with the tickers, but otherwise the same code.

**Comment by craig2sigma** [comment] 2024-03-13 16:13
It looks like the %change values that did return are just 100x larger than before. If that's the case, easy fix on my end

**Comment by Futur3H4wk** [comment] 2024-03-13 16:35
All good for me now, Thanks to all you smart hardworking types. Mostly I do crypto so Yahoo is my only option, my stock and IRA holdings are limited. Wish I had thought of changing my location with my VPN, but of course that is global to my system and some of my other software needs to be where it seems to be.

**Comment by Futur3H4wk** [comment] 2024-03-13 16:38
I change the extention name before I add it, for exampe this on is Financials-Extension3-5-0.oxt and I don't have any trouble installing or using. But if a new one comes out it's hard to tell.

**Comment by techman2423** [comment] 2024-03-13 17:06
i installed 3.5.0 and some of the fields loaded but still having issues with some of the yahoo requests....here's a pic.  "last price" is working  and % change is out of whack, but i got NA for the rest...
![Screenshot](https://github.com/cmallwitz/Financials-Extension/assets/158190858/304a54d0-06de-406a-820c-3012efc0f7f3)

**Comment by techman2423** [comment] 2024-03-15 00:31
I'm still getting these fields above (pic) that are #N/A...any ideas what i need to do?

**Comment by Durhammer3111** [comment] 2024-03-22 00:16
I opened a new instance of the Yahoo wackiness:

https://github.com/cmallwitz/Financials-Extension/issues/101

...but figure I oughta also mention it here. IT AIN'T WORKING, GANG!

**Comment by Futur3H4wk** [comment] 2024-04-03 04:53
everything crashed again tonight. way to druck to troubleshoot. tag your it

**Comment by estianic** [comment] 2024-04-03 09:06
Works fine here, but I guess that is because I still get the old style Yahoo Finance:
https://finance.yahoo.com/about/whatsnew

@cmallwitz 
Old style quote pages can be accessed like this:
https://finance.yahoo.com/quote/SPY?.neo_opt=0

**Comment by estianic** [comment] 2024-04-15 13:21
The inevitable has happened, Yahoo is now showing me the new Yahoo Finance layout. I can choose to go back to the classic layout, but that does not change the behaviour of the Financials-Extension.

LAST_PRICE still works fine
CHANGE_IN_PERCENT works but the result is multiplied by 100
BID and ASK show #N/A

I haven't tried the other data points.

Example html file is attached.

[iShares Semiconductor ETF (SOXX) Stock Price, News, Quote & History - Yahoo Finance.html.zip](https://github.com/cmallwitz/Financials-Extension/files/14979562/iShares.Semiconductor.ETF.SOXX.Stock.Price.News.Quote.History.-.Yahoo.Finance.html.zip)

**Comment by Durhammer3111** [comment] 2024-05-01 12:30
Huzzah!

⁣Get BlueMail for Android ​

**Comment by cmallwitz** [comment] 2024-05-01 17:41
I published a new [version  3.6.0](https://github.com/cmallwitz/Financials-Extension/releases/tag/3.6.0) - if current version is working for you, I would wait with the update. if you are getting loads of N/As at the moment, try this new version and let me know if things improve.

**Comment by schmani-db** [comment] 2024-05-01 18:01
> I published a new [version 3.6.0](https://github.com/cmallwitz/Financials-Extension/releases/tag/3.6.0) - if current version is working for you, I would wait with the update. if you are getting loads of N/As at the moment, try this new version and let me know if things improve.

Thanks a lot, the new version resolves the N/A issue!

**Comment by Durhammer3111** [comment] 2024-05-01 22:50
Very nice! And while I just tested after hours, it does seem to be a LOT quicker!!!!

**Comment by spacecatz03** [comment] 2024-05-02 02:25
I didn't have any issues with N/A but tried new version, worksheet opens noticeably quicker now. Great job with this!

**Comment by Durhammer3111** [comment] 2024-05-10 15:59
Aaarrrggghhhh. Just as @spacecatz03 reported yesterday, today suddenly everything comes back #NA. I don't have the previous version to roll back to (maybe it's in the resources area, I'll check). Glad I kept my FT version, though the portfolio is way behind my trades now.

**Comment by cmallwitz** [comment] 2024-05-17 16:56
Closing this - try new version 3.6.1

**Closed by cmallwitz** 2024-05-17 16:56 UTC
