### ISSUE TITLE
General failure with extension

### ISSUE THREAD

**Issue by Durhammer3111** [cmallwitz/Financials-Extension#77] opened 2023-01-13 15:48 UTC
Nothing is being returned today.  Extension log is full of entries like this:

2023-01-13 10:38:22,792 financials_yahoo ERROR BaseException ticker=YTEN datacode=69
Traceback (most recent call last):
  File "/home/XXXXXX/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu27888i4v5nk.tmp_/Financials-Extension.oxt/financials_yahoo.py", line 201, in getRealtimeSummary
    found = root.findall(f".//fin-streamer[@data-symbol='{ticker}']")
AttributeError: 'NoneType' object has no attribute 'findall'

The HTML files only contain (using the one for the above ticker, but they're all alike):

**Comment by cmallwitz** [comment] 2023-01-20 16:10
Closing as duplicate of https://github.com/cmallwitz/Financials-Extension/issues/80

**Closed by cmallwitz** 2023-01-20 16:10 UTC
