### ISSUE TITLE
Problem with some Swedish stocks

### ISSUE THREAD

**Issue by andreas-lindgren** [cmallwitz/Financials-Extension#64] opened 2022-11-19 14:55 UTC
Before I describe my issue, I want to thank you for creating this plugin. I really like it.

I mainly use two functions:
21 and 104

The problem is that I get the error code N/A for most Swedish stocks and the log don´t give me any help. 

This is the format I have on the code I add in Libreoffice:
`=GETREALTIME("VALMT.HE";104;"FT")` - this is a Finnish stock
`=GETREALTIME("SECU-B.ST";104;"FT")` - this is a Swedish stock that gives me the error code N/A

So my question is why this happen? Can you take a look at this, because I don´t understand why the Swedish stocks don´t work. I also want to point out that I have tested this on Windows 10 only, so I'm not sure if it works on Linux or macOS.

**Comment by cmallwitz** [comment] 2022-11-19 18:01
I think the problem is your symbols are wrong for FT 

For instance for VALMT.HE, I would expect VALMT:HEX - please check the argument to this URL for [VALMT:HEX](https://markets.ft.com/data/equities/tearsheet/summary?s=VALMT:HEX) - interestingly, if you change the argument at the end of the URL to VALMT.HE it will redirect back to the version with VALMT:HEX

FT doesn't seem to do this for SECU-B.ST though - you want SECU B:STO (note the space in there) - check this  [URL](https://markets.ft.com/data/equities/tearsheet/summary?s=SECU%20B:STO)

Unfortunately "symbology" is a problem across all exchanges world wide and I don't try address it in the extension because I can't consistently for every one. But you could have an additional tab in your spread sheet with the list of symbols you need for Yahoo and FT and switch between them with a VLOOKUP function to pick the right one.

**Comment by andreas-lindgren** [comment] 2022-11-20 08:58
Thank you so much.

I had messed up FT with YAHOO, so to change FT to YAHOO solved my problem. It seems like I had not read the instruction properly, but now when I read it again it was clear why it was not working.

**Comment by cmallwitz** [comment] 2023-01-02 16:59
Closing...

**Closed by cmallwitz** 2023-01-02 16:59 UTC
