### ISSUE TITLE
FT processed one request but fails on others

### ISSUE THREAD

**Issue by jbourvic** [cmallwitz/Financials-Extension#78] opened 2023-01-16 20:42 UTC
I was doing some research today and just quickly added some preferred stocks to my list. Yahoo was giving errors (site must be under maintenance) so I switched to FT. Well, FT handles preferred stocks completely differently (a BML-PG has to become BML PR G:NYQ for FT). I thought everything was going to be okay when I found that FT processed one request just fine but other requests produced errors (see attached).

I included the string of what was in the GETREALTIME cell to insure I didn't have the formula wrong.

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.4.3.2 (Windows)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>

BML PR G:NYQ | 02-14 | 0.343 | 02/13/23 | 20 |   | '=GETREALTIME(A34,21,"FT") |   | 19.84
-- | -- | -- | -- | -- | -- | -- | -- | --
BML PR H:NYQ | 02-14 | 0.3441 | 02/13/23 | 20 |   | '=GETREALTIME(A35,21,"FT") |   | '<' not supported between instances of 'float' and 'NoneType'

</body>

</html>

I hope this is readable. Is there a reason for the error? The FT site show the data just fine.

**Comment by cmallwitz** [comment] 2023-01-16 22:27
Thanks for the report! I have the feeling the extension is having a problem to recover after there was an error on an earlier request. I will take a look at this. In the meantime it might help to close all of LibreOffice/Calc completely and check if the data is OK afterwards (this would reset any internal state)

**Comment by cmallwitz** [comment] 2023-01-20 16:12
I have published a new version that hopefully addresses some shortcomings. Please close LibreCalc completely and use either a blank/new spreatsheet or the attached examples.ods to see if the extension is working in general or there is a problem with you spreadsheet itself.

Closing as duplicate of https://github.com/cmallwitz/Financials-Extension/issues/80 (not a FT/Yahoo specific underlying problem)

**Closed by cmallwitz** 2023-01-20 16:12 UTC
